/**
 * Profile: web-ai-split — Next.js frontend + FastAPI backend.
 */

import type { FeatureMapping, ScaffoldFile } from '@hadk/core';
import { type ProfileContext, type ProfileDefinition, mkFile, featureComponentName } from './profiles.js';

function generateFiles(ctx: ProfileContext): ScaffoldFile[] {
  const { projectName, features, featureMapping, demoFlow, wowMoment } = ctx;
  const files: ScaffoldFile[] = [];

  // ─── Frontend: package.json ────────────────────────────────────────────
  files.push(mkFile('frontend/package.json', JSON.stringify({
    name: `${projectName}-frontend`,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev -p 3000',
      build: 'next build',
      start: 'next start',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      next: '^15.1.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      '@types/node': '^22.10.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      typescript: '^5.7.0',
      tailwindcss: '^4.0.0',
      '@tailwindcss/postcss': '^4.0.0',
    },
  }, null, 2) + '\n'));

  files.push(mkFile('frontend/tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  }, null, 2) + '\n'));

  files.push(mkFile('frontend/next.config.ts', `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return [
      { source: '/api/:path*', destination: 'http://localhost:8000/api/:path*' },
    ];
  },
};

export default nextConfig;
`));

  files.push(mkFile('frontend/.env.example', `# Frontend environment
NEXT_PUBLIC_API_URL=http://localhost:8000
`));

  files.push(mkFile('frontend/src/app/layout.tsx', `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = { title: '${projectName}' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`));

  files.push(mkFile('frontend/src/app/globals.css', `@import 'tailwindcss';

body {
  background: #0a0a0f;
  color: #ededed;
  font-family: system-ui, sans-serif;
}
`));

  files.push(mkFile('frontend/src/app/page.tsx', `'use client';

import { useState } from 'react';

export default function Home() {
  const [input, setInput] = useState('');
  const [result, setResult] = useState<string | null>(null);

  async function run() {
    const res = await fetch('/api/process', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ input }),
    });
    const data = await res.json();
    setResult(JSON.stringify(data, null, 2));
  }

  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-bold mb-8">${projectName}</h1>
      <div className="w-full max-w-xl">
        <textarea
          className="w-full bg-neutral-900 border border-neutral-700 rounded-lg p-3 mb-4"
          rows={3}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Demo input..."
        />
        <button onClick={run} className="px-6 py-2 bg-indigo-600 rounded-lg font-medium">
          Run
        </button>
        {result && <pre className="mt-4 p-4 bg-neutral-900 rounded-lg text-sm">{result}</pre>}
      </div>
    </main>
  );
}
`));

  files.push(mkFile('frontend/postcss.config.mjs', `const config = { plugins: ['@tailwindcss/postcss'] };
export default config;
`));

  files.push(mkFile('frontend/.gitignore', `node_modules/
.next/
.env.local
`));

  // ─── Backend: FastAPI ──────────────────────────────────────────────────
  files.push(mkFile('backend/requirements.txt', `fastapi>=0.115.0
uvicorn[standard]>=0.34.0
pydantic>=2.10.0
openai>=1.58.0
python-dotenv>=1.0.0
httpx>=0.28.0
pytest>=8.3.0
`));

  files.push(mkFile('backend/app/main.py', `"""${projectName} — FastAPI backend. Generated by HADK scaffold engine."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.health import router as health_router
from app.api.process import router as process_router

app = FastAPI(title="${projectName}", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health_router, prefix="/api")
app.include_router(process_router, prefix="/api")
`));

  files.push(mkFile('backend/app/__init__.py', ''));
  files.push(mkFile('backend/app/api/__init__.py', ''));

  files.push(mkFile('backend/app/api/health.py', `from fastapi import APIRouter
from datetime import datetime, timezone

router = APIRouter()


@router.get("/health")
async def health():
    return {
        "status": "ok",
        "service": "${projectName}-backend",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
`));

files.push(mkFile('backend/app/api/process.py', `import os

from fastapi import APIRouter, Header, HTTPException
from pydantic import BaseModel, Field

from app.core.ai import invoke_ai

router = APIRouter()


class ProcessRequest(BaseModel):
    input: str = Field(max_length=8000)


@router.post("/process")
async def process(req: ProcessRequest, authorization: str | None = Header(default=None)):
    fallback = os.getenv("DEMO_FALLBACK_MODE", "true") == "true" or not os.getenv("OPENAI_API_KEY")
    configured_token = os.getenv("DEMO_API_TOKEN")
    if not fallback and (not configured_token or authorization != f"Bearer {configured_token}"):
        raise HTTPException(status_code=401, detail="Authentication required for live inference")
    result = await invoke_ai(req.input)
    return {"result": result}
`));

  files.push(mkFile('backend/app/core/__init__.py', ''));

  files.push(mkFile('backend/app/core/ai.py', `"""AI client with deterministic fallback mode."""

import os
import time

FALLBACK_RESPONSE = (
    "Deterministic fallback response. The core mechanism works end-to-end — "
    "set OPENAI_API_KEY for live inference."
)


async def invoke_ai(prompt: str) -> dict:
    start = time.time()
    api_key = os.getenv("OPENAI_API_KEY", "")
    fallback = os.getenv("DEMO_FALLBACK_MODE", "true") == "true" or not api_key

    if fallback:
        return {
            "text": FALLBACK_RESPONSE,
            "model": "fallback-deterministic",
            "fallback": True,
            "latency_ms": int((time.time() - start) * 1000),
        }

    from openai import AsyncOpenAI

    client = AsyncOpenAI(api_key=api_key, base_url=os.getenv("OPENAI_BASE_URL"))
    completion = await client.chat.completions.create(
        model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1024,
    )
    return {
        "text": completion.choices[0].message.content or "",
        "model": os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        "fallback": False,
        "latency_ms": int((time.time() - start) * 1000),
    }
`));

  files.push(mkFile('backend/.env.example', `# Backend environment
OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4o-mini
DEMO_FALLBACK_MODE=true
DEMO_API_TOKEN=replace-with-a-long-random-token-for-live-demo-access
`));

  files.push(mkFile('backend/.env', `OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4o-mini
DEMO_FALLBACK_MODE=true
`));

  files.push(mkFile('backend/tests/test_health.py', `from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health():
    response = client.get("/api/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"


def test_process_fallback():
    response = client.post("/api/process", json={"input": "demo test"})
    assert response.status_code == 200
    data = response.json()
    assert data["result"]["fallback"] is True
`));

  files.push(mkFile('backend/render.yaml', `services:
  - type: web
    name: ${projectName}-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEMO_FALLBACK_MODE
        value: "false"
`));

  files.push(mkFile('backend/.gitignore', `__pycache__/
*.pyc
.venv/
.env
`));

  // ─── Feature files ─────────────────────────────────────────────────────
  for (const featureId of features) {
    const mapping = featureMapping[featureId];
    if (!mapping) continue;
    const slug = featureId.replace(/_/g, '-');

    for (const service of mapping.services) {
      const pyPath = service.replace(/^src\/core\//, 'backend/app/core/').replace(/\.ts$/, '.py').replace(/-/g, '_');
      files.push(mkFile(pyPath, `"""Service: ${featureId} — implement core business logic here."""


async def execute(data: dict) -> dict:
    # TODO: implement core mechanism for ${featureId}
    return {"success": True, "result": data}
`));
    }

    for (const ui of mapping.ui) {
      const uiPath = ui.replace(/^components\//, 'frontend/src/components/');
      const comp = featureComponentName(featureId);
      files.push(mkFile(uiPath, `'use client';

// Feature: ${featureId}
export function ${comp}() {
  return (
    <div className="p-4 border border-neutral-800 rounded-lg">
      <h3 className="font-semibold mb-2">${comp}</h3>
      <p className="text-sm text-neutral-400">Feature "${featureId}" — implement UI here.</p>
    </div>
  );
}
`));
    }
  }

  // ─── Root orchestration ────────────────────────────────────────────────
  files.push(mkFile('package.json', JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      'dev:frontend': 'pnpm --dir frontend dev',
      'dev:backend': 'cd backend && uvicorn app.main:app --reload --port 8000',
      dev: 'concurrently "pnpm dev:frontend" "pnpm dev:backend"',
      'demo:reset': 'echo "Reset demo state to baseline"',
      test: 'cd backend && pytest',
    },
    devDependencies: { concurrently: '^9.1.0' },
  }, null, 2) + '\n'));

  files.push(mkFile('README.md', `# ${projectName}

Generated by the HADK scaffold engine (profile: web-ai-split).

## Architecture

\`\`\`
User → localhost:3000 (Next.js) → localhost:8000 (FastAPI) → AI provider
\`\`\`

## Quick Start

\`\`\`bash
# Backend
cd backend && python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload --port 8000

# Frontend (separate terminal)
cd frontend && pnpm install && pnpm dev
\`\`\`

Fallback mode is enabled by default — no API keys needed.

## Health Check

\`\`\`bash
curl http://localhost:8000/api/health
\`\`\`

## Tests

\`\`\`bash
cd backend && pytest
\`\`\`
`));

  files.push(mkFile('.gitignore', `node_modules/
.next/
__pycache__/
.venv/
.env.local
`));

  return files;
}

function mapFeature(featureId: string, featureName: string): FeatureMapping {
  const slug = featureId.replace(/_/g, '-');
  return {
    routes: [`backend/app/api/${slug.replace(/-/g, '_')}.py`],
    ui: [`components/${slug}.tsx`],
    services: [`src/core/${slug}/service.ts`],
    tests: [`backend/tests/test_${slug.replace(/-/g, '_')}.py`],
  };
}

export const webAiSplitProfile: ProfileDefinition = {
  name: 'web-ai-split',
  description: 'Next.js frontend + FastAPI backend with AI integration and fallback mode',
  stack: ['next.js', 'react', 'typescript', 'fastapi', 'python', 'openai'],
  startupCommand: 'pnpm dev',
  healthCheck: 'curl http://localhost:8000/api/health',
  postInstallCommands: ['cd backend && pip install -r requirements.txt'],
  generateFiles,
  mapFeature,
};
