/**
 * Profile: blockchain — web3 dApp with smart contract, wagmi frontend.
 */

import type { FeatureMapping, ScaffoldFile } from '@hadk/core';
import { type ProfileContext, type ProfileDefinition, mkFile, featureComponentName } from './profiles.js';

function generateFiles(ctx: ProfileContext): ScaffoldFile[] {
  const { projectName, features, featureMapping, demoFlow, wowMoment } = ctx;
  const files: ScaffoldFile[] = [];

  // ─── Root package.json ─────────────────────────────────────────────────
  files.push(mkFile('package.json', JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      'chain:compile': 'cd contracts && forge build',
      'chain:test': 'cd contracts && forge test',
      'chain:deploy': 'cd contracts && forge script script/Deploy.s.sol --broadcast',
      'demo:reset': 'tsx scripts/reset-demo-data.ts',
    },
    dependencies: {
      next: '^15.1.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
      wagmi: '^2.14.0',
      viem: '^2.21.0',
      '@tanstack/react-query': '^5.62.0',
    },
    devDependencies: {
      '@types/node': '^22.10.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      typescript: '^5.7.0',
      vitest: '^3.0.0',
      tsx: '^4.19.0',
      tailwindcss: '^4.0.0',
      '@tailwindcss/postcss': '^4.0.0',
    },
  }, null, 2) + '\n'));

  files.push(mkFile('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  }, null, 2) + '\n'));

  files.push(mkFile('next.config.ts', `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  webpack: (config) => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    return config;
  },
};

export default nextConfig;
`));

  // ─── Smart contract (Foundry) ──────────────────────────────────────────
  files.push(mkFile('contracts/src/Core.sol', `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * ${projectName} — core mechanism contract.
 * Generated by HADK scaffold engine (profile: blockchain).
 */
contract Core {
    struct Entry {
        address owner;
        string payload;
        uint256 timestamp;
    }

    Entry[] public entries;
    mapping(address => uint256) public entryCount;

    event EntryCreated(uint256 indexed id, address indexed owner, string payload);

    function create(string calldata payload) external returns (uint256 id) {
        id = entries.length;
        entries.push(Entry({ owner: msg.sender, payload: payload, timestamp: block.timestamp }));
        entryCount[msg.sender]++;
        emit EntryCreated(id, msg.sender, payload);
    }

    function get(uint256 id) external view returns (Entry memory) {
        require(id < entries.length, "not found");
        return entries[id];
    }

    function total() external view returns (uint256) {
        return entries.length;
    }
}
`));

  files.push(mkFile('contracts/test/Core.t.sol', `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Core} from "../src/Core.sol";

contract CoreTest is Test {
    Core core;

    function setUp() public {
        core = new Core();
    }

    function test_Create() public {
        uint256 id = core.create("demo payload");
        assertEq(id, 0);
        assertEq(core.total(), 1);

        Core.Entry memory e = core.get(0);
        assertEq(e.payload, "demo payload");
        assertEq(e.owner, address(this));
    }

    function test_EntryCount() public {
        core.create("a");
        core.create("b");
        assertEq(core.entryCount(address(this)), 2);
    }
}
`));

  files.push(mkFile('contracts/script/Deploy.s.sol', `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Script} from "forge-std/Script.sol";
import {Core} from "../src/Core.sol";

contract Deploy is Script {
    function run() external {
        vm.startBroadcast();
        Core core = new Core();
        vm.stopBroadcast();
        console.log("Core deployed at:", address(core));
    }
}
`));

  files.push(mkFile('contracts/foundry.toml', `[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
`));

  files.push(mkFile('contracts/.gitignore', `out/
cache/
lib/
broadcast/
`));

  // ─── Frontend: wagmi config ────────────────────────────────────────────
  files.push(mkFile('src/lib/wagmi.ts', `import { http, createConfig } from 'wagmi';
import { localhost, sepolia } from 'wagmi/chains';

export const wagmiConfig = createConfig({
  chains: [localhost, sepolia],
  transports: {
    [localhost.id]: http(),
    [sepolia.id]: http(),
  },
});

// Core contract ABI (minimal — extend as the contract grows)
export const coreAbi = [
  {
    type: 'function',
    name: 'create',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'payload', type: 'string' }],
    outputs: [{ name: 'id', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'total',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'EntryCreated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'payload', type: 'string', indexed: false },
    ],
  },
] as const;

export const CORE_ADDRESS = (process.env.NEXT_PUBLIC_CORE_ADDRESS ?? '0x0000000000000000000000000000000000000000') as \`0x\${string}\`;
`));

  files.push(mkFile('src/app/layout.tsx', `import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = { title: '${projectName}' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
`));

  files.push(mkFile('src/app/providers.tsx', `'use client';

import { WagmiProvider } from 'wagmi';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { wagmiConfig } from '@/lib/wagmi';
import { useState } from 'react';

export function Providers({ children }: { children: React.ReactNode }) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </WagmiProvider>
  );
}
`));

  files.push(mkFile('src/app/globals.css', `@import 'tailwindcss';

body {
  background: #0a0a0f;
  color: #ededed;
  font-family: system-ui, sans-serif;
}
`));

  files.push(mkFile('src/app/page.tsx', `'use client';

import { useAccount, useConnect, useDisconnect } from 'wagmi';
import { injected } from 'wagmi/connectors';

export default function Home() {
  const { isConnected } = useAccount();
  const { connect } = useConnect();
  const { disconnect } = useDisconnect();

  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-bold mb-2">${projectName}</h1>
      <p className="text-neutral-400 mb-8">On-chain demo prototype</p>
      {isConnected ? (
        <button onClick={() => disconnect()} className="px-6 py-2 bg-neutral-700 rounded-lg">
          Disconnect
        </button>
      ) : (
        <button
          onClick={() => connect({ connector: injected() })}
          className="px-6 py-2 bg-indigo-600 rounded-lg font-medium"
        >
          Connect Wallet
        </button>
      )}
      <p className="mt-4 text-xs text-neutral-500">
        Demo tip: run a local chain with \`anvil\` for a wallet-connected demo without testnet gas.
      </p>
    </main>
  );
}
`));

  // ─── Health endpoint ───────────────────────────────────────────────────
  files.push(mkFile('src/app/api/health/route.ts', `import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    status: 'ok',
    service: '${projectName}',
    chain_configured: Boolean(process.env.NEXT_PUBLIC_CORE_ADDRESS),
    timestamp: new Date().toISOString(),
  });
}
`));

  files.push(mkFile('.env.example', `# ${projectName} — environment
NEXT_PUBLIC_CORE_ADDRESS=
DEMO_FALLBACK_MODE=true
`));

  files.push(mkFile('.env.local', `NEXT_PUBLIC_CORE_ADDRESS=
DEMO_FALLBACK_MODE=true
`));

  // ─── Feature files ─────────────────────────────────────────────────────
  for (const featureId of features) {
    const mapping = featureMapping[featureId];
    if (!mapping) continue;
    const slug = featureId.replace(/_/g, '-');
    const comp = featureComponentName(featureId);

    for (const ui of mapping.ui) {
      files.push(mkFile(ui, `'use client';

// Feature: ${featureId}
export function ${comp}() {
  return (
    <div className="p-4 border border-neutral-800 rounded-lg">
      <h3 className="font-semibold mb-2">${comp}</h3>
      <p className="text-sm text-neutral-400">Feature "${featureId}" — implement here.</p>
    </div>
  );
}
`));
    }

    for (const service of mapping.services) {
      files.push(mkFile(service, `/**
 * Service: ${featureId}
 * On-chain interaction logic — use viem/wagmi to call the Core contract.
 */

export async function execute${comp}(data: unknown) {
  // TODO: implement contract interaction for ${featureId}
  return { success: true, result: data };
}
`));
    }

    for (const test of mapping.tests) {
      files.push(mkFile(test, `import { describe, it, expect } from 'vitest';

describe('${featureId}', () => {
  it('placeholder — implement after contract wiring', () => {
    expect(true).toBe(true);
  });
});
`));
    }
  }

  // ─── Demo tooling ──────────────────────────────────────────────────────
  files.push(mkFile('scripts/reset-demo-data.ts', `/**
 * Reset demo state: restart anvil for a clean chain, clear local UI state.
 * Run: pnpm demo:reset
 */
console.log('Demo reset: restart anvil (anvil &) and refresh the frontend.');
`));

  files.push(mkFile('tests/smoke.test.ts', `import { describe, it, expect } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

describe('smoke: ${projectName}', () => {
  it('has a package.json', () => {
    expect(existsSync(join(process.cwd(), 'package.json'))).toBe(true);
  });
  it('has the core contract', () => {
    expect(existsSync(join(process.cwd(), 'contracts/src/Core.sol'))).toBe(true);
  });
  it('has a health endpoint', () => {
    expect(existsSync(join(process.cwd(), 'src/app/api/health/route.ts'))).toBe(true);
  });
});
`));

  files.push(mkFile('vitest.config.ts', `import { defineConfig } from 'vitest/config';
import { resolve } from 'node:path';

export default defineConfig({
  test: { environment: 'node', include: ['tests/**/*.test.ts'] },
  resolve: { alias: { '@': resolve(__dirname, './src') } },
});
`));

  files.push(mkFile('postcss.config.mjs', `const config = { plugins: ['@tailwindcss/postcss'] };
export default config;
`));

  files.push(mkFile('.gitignore', `node_modules/
.next/
.env.local
out/
cache/
`));

  files.push(mkFile('README.md', `# ${projectName}

Generated by the HADK scaffold engine (profile: blockchain).

## Quick Start

\`\`\`bash
pnpm install
pnpm dev              # frontend on :3000
anvil                 # local chain on :8545 (install via foundry)
\`\`\`

## Contracts

\`\`\`bash
cd contracts
forge build
forge test
\`\`\`

## Health Check

\`\`\`bash
curl http://localhost:3000/api/health
\`\`\`

## Demo Flow

1. Start anvil for a clean local chain
2. Deploy: \`forge script script/Deploy.s.sol --broadcast\`
3. Set NEXT_PUBLIC_CORE_ADDRESS in .env.local
4. Connect a wallet (MetaMask pointed at localhost:8545)
\`\`\`
`));

  return files;
}

function mapFeature(featureId: string, featureName: string): FeatureMapping {
  const slug = featureId.replace(/_/g, '-');
  return {
    routes: [`src/app/api/${slug}/route.ts`],
    ui: [`src/components/${slug}.tsx`],
    services: [`src/core/${slug}/service.ts`],
    tests: [`tests/${slug}.test.ts`],
  };
}

export const blockchainProfile: ProfileDefinition = {
  name: 'blockchain',
  description: 'Web3 dApp: Next.js + wagmi frontend, Foundry/Solidity smart contract, local-chain demo',
  stack: ['next.js', 'react', 'typescript', 'wagmi', 'viem', 'solidity', 'foundry'],
  startupCommand: 'pnpm dev',
  healthCheck: 'curl http://localhost:3000/api/health',
  postInstallCommands: ['cd contracts && forge build'],
  generateFiles,
  mapFeature,
};
